/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as CreateRouteImport } from './routes/create'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as WikiSlugIndexRouteImport } from './routes/wiki.$slug.index'
import { Route as WikiSlugHistoryRouteImport } from './routes/wiki.$slug.history'
import { Route as WikiSlugEditRouteImport } from './routes/wiki.$slug.edit'
import { Route as WikiSlugDiscussRouteImport } from './routes/wiki.$slug.discuss'
import { Route as WikiSlugRevisionsRevIdRouteImport } from './routes/wiki.$slug.revisions.$revId'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugIndexRoute = WikiSlugIndexRouteImport.update({
  id: '/wiki/$slug/',
  path: '/wiki/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugHistoryRoute = WikiSlugHistoryRouteImport.update({
  id: '/wiki/$slug/history',
  path: '/wiki/$slug/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugEditRoute = WikiSlugEditRouteImport.update({
  id: '/wiki/$slug/edit',
  path: '/wiki/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugDiscussRoute = WikiSlugDiscussRouteImport.update({
  id: '/wiki/$slug/discuss',
  path: '/wiki/$slug/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRevisionsRevIdRoute = WikiSlugRevisionsRevIdRouteImport.update({
  id: '/wiki/$slug/revisions/$revId',
  path: '/wiki/$slug/revisions/$revId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/moderation': typeof ModerationRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/wiki/$slug/discuss': typeof WikiSlugDiscussRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/': typeof WikiSlugIndexRoute
  '/wiki/$slug/revisions/$revId': typeof WikiSlugRevisionsRevIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/moderation': typeof ModerationRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/wiki/$slug/discuss': typeof WikiSlugDiscussRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug': typeof WikiSlugIndexRoute
  '/wiki/$slug/revisions/$revId': typeof WikiSlugRevisionsRevIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/moderation': typeof ModerationRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof WatchlistRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/wiki/$slug/discuss': typeof WikiSlugDiscussRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/': typeof WikiSlugIndexRoute
  '/wiki/$slug/revisions/$revId': typeof WikiSlugRevisionsRevIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/create'
    | '/moderation'
    | '/search'
    | '/watchlist'
    | '/profile/$username'
    | '/wiki/$slug/discuss'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
    | '/wiki/$slug/'
    | '/wiki/$slug/revisions/$revId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/create'
    | '/moderation'
    | '/search'
    | '/watchlist'
    | '/profile/$username'
    | '/wiki/$slug/discuss'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
    | '/wiki/$slug'
    | '/wiki/$slug/revisions/$revId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/browse'
    | '/create'
    | '/moderation'
    | '/search'
    | '/watchlist'
    | '/profile/$username'
    | '/wiki/$slug/discuss'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
    | '/wiki/$slug/'
    | '/wiki/$slug/revisions/$revId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CreateRoute: typeof CreateRoute
  ModerationRoute: typeof ModerationRoute
  SearchRoute: typeof SearchRoute
  WatchlistRoute: typeof WatchlistRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  WikiSlugDiscussRoute: typeof WikiSlugDiscussRoute
  WikiSlugEditRoute: typeof WikiSlugEditRoute
  WikiSlugHistoryRoute: typeof WikiSlugHistoryRoute
  WikiSlugIndexRoute: typeof WikiSlugIndexRoute
  WikiSlugRevisionsRevIdRoute: typeof WikiSlugRevisionsRevIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/': {
      id: '/wiki/$slug/'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug/'
      preLoaderRoute: typeof WikiSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/history': {
      id: '/wiki/$slug/history'
      path: '/wiki/$slug/history'
      fullPath: '/wiki/$slug/history'
      preLoaderRoute: typeof WikiSlugHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/edit': {
      id: '/wiki/$slug/edit'
      path: '/wiki/$slug/edit'
      fullPath: '/wiki/$slug/edit'
      preLoaderRoute: typeof WikiSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/discuss': {
      id: '/wiki/$slug/discuss'
      path: '/wiki/$slug/discuss'
      fullPath: '/wiki/$slug/discuss'
      preLoaderRoute: typeof WikiSlugDiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/revisions/$revId': {
      id: '/wiki/$slug/revisions/$revId'
      path: '/wiki/$slug/revisions/$revId'
      fullPath: '/wiki/$slug/revisions/$revId'
      preLoaderRoute: typeof WikiSlugRevisionsRevIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CreateRoute: CreateRoute,
  ModerationRoute: ModerationRoute,
  SearchRoute: SearchRoute,
  WatchlistRoute: WatchlistRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  WikiSlugDiscussRoute: WikiSlugDiscussRoute,
  WikiSlugEditRoute: WikiSlugEditRoute,
  WikiSlugHistoryRoute: WikiSlugHistoryRoute,
  WikiSlugIndexRoute: WikiSlugIndexRoute,
  WikiSlugRevisionsRevIdRoute: WikiSlugRevisionsRevIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
